name: quantum
version: '0.1'
summary: Quantum is a fork of Ansible.
description: |
    Quantum is a fork of Ansible.
    
grade: devel 
confinement: devmode 
base: core20

apps:
  quantum:
    command: quantum
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - mount-observe
      - system-files
      - personal-files
      
parts: 
  quantum:
    source: https://github.com/kz6fittycent/quantum/
    source-type: git
    plugin: python
      
    build-packages:
      - python3
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-setuptools
      - python3-cryptography        
      
    stage-packages:
      - python3
      - python3-jinja2
      - python3-yaml
      - python3-paramiko
      - python3-setuptools
      - python3-cryptography      
