name: quantum
version: '0.1'
summary: Quantum is a fork of Ansible.
description: |
    Quantum is a fork of Ansible.
    
grade: devel 
confinement: devmode 
base: core18

apps:
  quantum:
    command: $SNAP/quantum
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - mount-observe
      - system-files
      - personal-files
      
parts: 
  quantum:
    source: https://github.com/kz6fittycent/quantum/
    source-type: git
    plugin: python
    python-version: python2
      
    build-packages:
      - python
      - python-jinja2
      - python-yaml
      - python-paramiko
      - python-setuptools
      - python-cryptography        
      
    stage-packages:
      - python
      - python-jinja2
      - python-yaml
      - python-paramiko
      - python-setuptools
      - python-cryptography      
