name: quantum
version: '0.1'
summary: Quantum is a fork of Ansible.
description: |
    Quantum is a fork of Ansible.
    
grade: devel 
confinement: devmode 
base: core20

apps:
  quantum:
    command: quantum
    command-chain: 
      - bin/homeishome-launch    
    environment: 
      LC_ALL: C.UTF-8
    plugs:
      - home
      - network
      - mount-observe
      - system-files
      - personal-files
      
parts: 
  quantum:
    source: https://github.com/kz6fittycent/quantum/
    source-type: git
    plugin: python
    requirements: [requirements.txt] 
    
    override-build: |
      python3 setup.py
      snapcraftctl build
    
  homeishome-launch:
    plugin: nil
    stage-snaps:
      - homeishome-launch             
